# ASSIGNMENT 4, NAME-SARISHTI, ROLL NUMBER-102317212

In [1]:
#QUES 1
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

# a) Addition of 2 to all elements
arr_add = arr + 2

# b) Multiply 3 with all elements
arr_multiply = arr * 3

# c) Divide all elements by 2
arr_divide = arr / 2

print("Original Array:", arr)
print("After Addition:", arr_add)
print("After Multiplication:", arr_multiply)
print("After Division:", arr_divide)

Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


In [2]:
#QUES 2
arr = np.array([1, 2, 3, 6, 4, 5])
arr_reversed = arr[::-1]

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
most_freq_x = np.bincount(x).argmax()
indices_x = np.where(x == most_freq_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 3, 3, 3])
most_freq_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_y)

print("Reversed Array:", arr_reversed)
print("Most Frequent Value in x:", most_freq_x, ", Indices:", indices_x[0])
print("Most Frequent Value in y:", most_freq_y, ", Indices:", indices_y[0])

Reversed Array: [5 4 6 3 2 1]
Most Frequent Value in x: 1 , Indices: [0 5 7 8]
Most Frequent Value in y: 3 , Indices: [4 7 8 9]


In [3]:
#QUES 3
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

element_a = arr_2d[0, 1]  # 1st row, 2nd column
element_b = arr_2d[2, 0]  # 3rd row, 1st column

print("Element at (1st row, 2nd col):", element_a)
print("Element at (3rd row, 1st col):", element_b)

Element at (1st row, 2nd col): 20
Element at (3rd row, 1st col): 70


In [4]:
#QUES 4
your_name_array = np.linspace(10, 100, 25)

print("Dimensions:", your_name_array.ndim)
print("Shape:", your_name_array.shape)
print("Total Elements:", your_name_array.size)
print("Data Type:", your_name_array.dtype)
print("Bytes Consumed:", your_name_array.nbytes)

reshaped_array = your_name_array.reshape(5, 5)
print("Reshaped Array:\n", reshaped_array)

Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Reshaped Array:
 [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


In [5]:
#QUES 5
ucs420_array = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])

mean_val = np.mean(ucs420_array)
median_val = np.median(ucs420_array)
max_val = np.max(ucs420_array)
min_val = np.min(ucs420_array)
unique_elements = np.unique(ucs420_array)

reshaped_array = ucs420_array.reshape(4, 3)

ucs420_resized = np.resize(ucs420_array, (2, 3))

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_elements)
print("Reshaped Array:\n", reshaped_array)
print("Resized Array:\n", ucs420_resized)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
