# ASSIGNMENT 5,NAME-SARISHTI, ROLL NUMBER-102317212

In [1]:
#ques1 
import numpy as np

gfg = np.matrix([[4, 1, 9], [2, 13, 1], [4, 5, 6]])

total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)

print("Total Sum:", total_sum)
print("Row-wise Sum:\n", row_sum)
print("Column-wise Sum:\n", col_sum)


Total Sum: 45
Row-wise Sum:
 [[14]
 [16]
 [15]]
Column-wise Sum:
 [[10 19 16]]


In [2]:
#ques 2 (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_arr = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]

print("Sorted Array:", sorted_arr)
print("Indices of Sorted Array:", sorted_indices)
print("4 Smallest Elements:", smallest_4)
print("5 Largest Elements:", largest_5)

Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


In [3]:
#ques 2 (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]

print("Integer Elements:", int_elements)
print("Float Elements:", float_elements)


Integer Elements: [1. 2. 3. 2.]
Float Elements: [1.2 2.2]


In [4]:
#ques 3
import numpy as np
first_initial = 'A'
last_initial = 'B'
X = ord(first_initial) + ord(last_initial) 
sales = np.array([X, X+50, X+100, X+150, X+200])  

tax_rate = (X % 5 + 5) / 100
tax = sales * tax_rate

discounted_sales = np.where(sales <= X+100, sales * 0.95, sales * 0.90)
sales_matrix = np.tile(sales, (3, 1)) 
increased_sales = sales_matrix + (sales_matrix * 0.02) 

print("Original Sales:", sales)
print("Tax Applied:", tax)
print("Discounted Sales:", discounted_sales)
print("Expanded Weekly Sales Matrix:\n", sales_matrix)
print("Sales Increased by 2%:\n", increased_sales)

Original Sales: [131 181 231 281 331]
Tax Applied: [ 7.86 10.86 13.86 16.86 19.86]
Discounted Sales: [124.45 171.95 219.45 252.9  297.9 ]
Expanded Weekly Sales Matrix:
 [[131 181 231 281 331]
 [131 181 231 281 331]
 [131 181 231 281 331]]
Sales Increased by 2%:
 [[133.62 184.62 235.62 286.62 337.62]
 [133.62 184.62 235.62 286.62 337.62]
 [133.62 184.62 235.62 286.62 337.62]]


In [ ]:
#ques 4

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)

y_square = x**2
y_sin = np.sin(x)
y_exp = np.exp(x)
y_log = np.log(np.abs(x) + 1)

plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.plot(x, y_square)
plt.title("y = x²")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)

plt.subplot(2, 2, 2)
plt.plot(x, y_sin)
plt.title("y = sin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)

plt.subplot(2, 2, 3)
plt.plot(x, y_exp)
plt.title("y = eˣ")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)

plt.subplot(2, 2, 4)
plt.plot(x, y_log)
plt.title("y = log(|x| + 1)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)

plt.tight_layout()
plt.show()

